package application;

import java.util.ArrayList;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class MediaMarkt {
	public static ArrayList<Cafetera> listaCafetera = new ArrayList<Cafetera>();	
	public static ArrayList<WebElement> listaNom = new ArrayList<WebElement>();
	public static ArrayList<WebElement> listaPre = new ArrayList<WebElement>();
	
	public static ArrayList<Cafetera> krupsMono(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.categoryTreeFirst")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> deLonghiMono(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.categoryTreeFirst")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> boschMono(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.categoryTreeFirst")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(3) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> philipsMono(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.categoryTreeFirst")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(4) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> tassimoMono(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.categoryTreeFirst")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(5) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> krupsSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> saecoSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> deLonghiSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(3) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> boschSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(4) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> juraSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(5) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> philipsSuper(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_730 > a:nth-child(1")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(6) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> krupsExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> saecoExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> deLonghiExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(3) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> ufesaExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(4) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> jataExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(5) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> orbegozoExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(6) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> whirlpoolExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(7) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> illiExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(8) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> osterExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(9) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> solacExpress(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_731 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> deLonghiGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> boschGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> philipsGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(3) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> moulinexGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(4) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> taurusGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(5) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> ufesaGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(6) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> jataGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(7) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> rushellGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(8) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> okGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(9) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> electroGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.filterElement:nth-child(10) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> wmfGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("#categoryFilterMoreBrands > div:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		controlador2.findElement(By.cssSelector("#categoryFilterViewMoreBrands")).click();
		Main.waitForPageLoad(controlador2);
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> tristarGoteo(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10000892 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("#categoryFilterMoreBrands > div:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		controlador2.findElement(By.cssSelector("#categoryFilterViewMoreBrands")).click();
		Main.waitForPageLoad(controlador2);
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> taurusTradicional(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10002237 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> jataTradicional(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10002237 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.filterElement:nth-child(2) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	public static ArrayList<Cafetera> menzTradicional(){
		WebDriver controlador2 = inicioFirefox();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#categoryTree_10002237 > a:nth-child(1)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("a.filterElement:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(3)")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("div.categoryFilter:nth-child(2) > div:nth-child(2) > select:nth-child(1) > option:nth-child(3)")).click();
		JavascriptExecutor jse = (JavascriptExecutor)controlador2;
		jse.executeScript("window.scrollBy(0,-250)", "");
		WebDriverWait waitingScrollKrupsMonoMM = new WebDriverWait(controlador2, 10);
		waitingScrollKrupsMonoMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.brandsFilterElement:nth-child(1) > a:nth-child(2)")));
		controlador2.findElement(By.cssSelector("div.brandsFilterElement:nth-child(3) > a:nth-child(2)")).click();
		Main.waitForPageLoad(controlador2);	
		listaNom = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'product1Description')]"));
		listaPre = (ArrayList<WebElement>) controlador2.findElements(By.xpath("//*[contains(@class, 'meta-bigprices')]"));				
		Main.waitForPageLoad(controlador2);
		listaCafetera = Main.llenarListaMM(listaNom, listaPre);
		controlador2.quit();
		return listaCafetera;	
	}
	
	
	public static WebDriver inicioFirefox(){
		String exe = "*\\geckodriver.exe";
		System.setProperty("webdriver.firefox.marionette", exe);
		DesiredCapabilities capacidad = DesiredCapabilities.firefox();
		capacidad.setCapability("marionette", true);
		@SuppressWarnings("deprecation")
		WebDriver controlador2 = new FirefoxDriver(capacidad);
		controlador2.get("https://www.mediamarkt.es/");
		controlador2.manage().window().maximize();
		WebDriverWait waitingCookiesMM = new WebDriverWait(controlador2, 10);
		waitingCookiesMM.until(ExpectedConditions.presenceOfElementLocated(By.id("close-cookies-law")));
		controlador2.findElement(By.id("close-cookies-law")).click();
		Main.waitForPageLoad(controlador2);
		controlador2.findElement(By.cssSelector("#world_hogar-jardin > a:nth-child(1)")).click();
		WebDriverWait waitingCafeMM = new WebDriverWait(controlador2, 10);
		waitingCafeMM.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("#category_hogar-jardin--ctg-cafe > a:nth-child(1)")));
		controlador2.findElement(By.cssSelector("#category_hogar-jardin--ctg-cafe > a:nth-child(1)")).click();
		return controlador2;
	}
}
